### ISSUE TITLE
Update for Storm 1.x?

### ISSUE THREAD

**Issue by et1975** [pmerienne/trident-ml#17]
Any plans to update it for Storm 1.x?

**Comment by miguelantonio** [comment]
@et1975 yes, expect one in a few days, also, I'm planning to release the framework to use rules in YAML files and other functionalities, that will be out in some weeks

**Comment by pmerienne** [comment]
@et1975 and @miguelantonio I've stopped development of trident-ml years ago!
I'm not planning to work on it again.

Please feel free to submit a PR, I still have time to review and merge PRs!

**Comment by ujfjhz** [comment]
@pmerienne why this project is stopped? I think ml on trident is a great idea.

**Comment by leerobert** [comment]
@ujfjhz because there are plenty of more community supported streaming tools for ML than storm
